#!/usr/bin/env python3
"""Inline content/chain.json into assets/js/chain-data.js.

The diagram must work from a local clone opened with file://, where fetch() of a
sibling JSON is blocked by the browser's origin rules. So the data ships as a
script that assigns to a global instead. content/chain.json stays the single
source; this file is generated, never hand-edited.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
src = ROOT / "content" / "chain.json"
out = ROOT / "assets" / "js" / "chain-data.js"

data = json.loads(src.read_text())
data.pop("$comment", None)
out.write_text(
    "/* GENERATED by tools/build_chain_data.py from content/chain.json — do not edit. */\n"
    "window.NOCTUA_CHAIN = " + json.dumps(data, indent=2, ensure_ascii=False) + ";\n"
)
print(f"chain-data.js written — {len(data['stages'])} stages, {len(data['lanes'])} lanes, "
      f"{len(data['sourceKinds'])} source kinds ({out.stat().st_size // 1024} KB)")
