#!/usr/bin/env python3
"""Inline i18n/*.json into assets/js/i18n-data.js.

Same reason as tools/build_chain_data.py: fetch() of a sibling JSON is blocked under
file://, and the site has to work from a local clone. The JSON files stay the single
source that Delta edits; this file is generated.
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
langs = {p.stem: json.loads(p.read_text()) for p in sorted((ROOT / "i18n").glob("*.json"))}

keysets = {lang: set(d) for lang, d in langs.items()}
base = next(iter(keysets.values()))
for lang, ks in keysets.items():
    if ks != base:
        raise SystemExit(f"FAIL {lang}.json key set differs: "
                         f"missing {sorted(base - ks)}, extra {sorted(ks - base)}")

out = ROOT / "assets" / "js" / "i18n-data.js"
out.write_text(
    "/* GENERATED by tools/build_i18n.py from i18n/*.json — do not edit. */\n"
    "window.NOCTUA_I18N = " + json.dumps(langs, indent=2, ensure_ascii=False) + ";\n"
)
print(f"i18n-data.js written — {', '.join(f'{l} {len(d)} keys' for l, d in langs.items())} "
      f"({out.stat().st_size // 1024} KB)")
