#!/usr/bin/env python3
"""
apply_layer.py — the GENERAL @LAYER writer for domain-forge HTML models.

Purpose
-------
Insert one pure-additive layer block into a domain-forge model. The output is
a strict BYTE SUPERSET of the input: every input byte is preserved and the
block is inserted just before the LAST `</body>`. The input file is never
modified. If the input already carries a layer with the same NAME, that block
is stripped first and replaced (create-or-update) — the only permitted
non-superset case, and it is reported on stdout.

This module is also importable by other skills:

    from apply_layer import apply_layer, domain_digest, list_layers, strip_layer, restamp_layers

    out_html = apply_layer(html, "chat", data_text, render_js, style_css=None,
                           data_type="application/json", produced_by="/model-chat",
                           version=1, noscript_html=None, produced_at=None)
    domain_digest(html)  -> "sha256:<hex>"   (digest of the canonical Turtle)
    turtle_body(html)    -> the canonical Turtle text the digest covers (None if absent)
    is_model(html)       -> bool (the canonical Turtle block is present)
    list_layers(html)    -> [ {name, version, produced_by, produced_at,
                               input_digest, reverts_by, start, end, header}, … ]
    find_layer(html, name) -> that entry, or None
    strip_layer(html, name) -> html without that layer (raises KeyError if absent)
    utc_now_iso()        -> "YYYY-MM-DDTHH:MM:SSZ" (the produced-at format)

/model-chat and /inferred-questions import this module (locating it as the
sibling `domain-forge/scripts`, overridable with --domain-forge-dir or
$DOMAIN_FORGE_DIR) and keep only their layer-specific data shaping, render JS
and CSS; there is no second copy of the block format or the digest.

Block layout (see references/future-skills.md, "The HTML layer contract"):

    <!-- @LAYER:start NAME vN
         produced-by: /skill-name
         produced-at: 2026-01-01T00:00:00Z
         input-digest: sha256:…
         reverts-by: open the file at input-digest (the predecessor)
     -->
    <script id="layer-NAME-data" type="application/json">…</script>
    <script id="layer-NAME-render" type="text/javascript">…</script>
    <style id="layer-NAME-style">…</style>            (optional)
    <noscript>…</noscript>                            (optional)
    <!-- @LAYER:end NAME -->

`input-digest` is "sha256:" + SHA-256 of the exact bytes between the
`<script id="domain-model" …>` open tag and its `</script>` — no
normalisation. /model-chat and /inferred-questions call this very function,
so digests are comparable across skills.

CLI
---
    apply_layer.py MODEL.html --layer NAME --data DATA_FILE --render RENDER_JS
                   [--style STYLE_CSS] [--data-type application/json]
                   [--produced-by "/skill-name"] [--version 1]
                   [--noscript NOSCRIPT_HTML_FILE] [--produced-at ISO-UTC]
                   --out OUT.html

    apply_layer.py MODEL.html --restamp (--out OUT.html | --in-place)

`--restamp` rewrites every layer's `input-digest` to the digest of the
file's CURRENT canonical Turtle. It is the deliberate, named operation for
the one legitimate case where a base model was edited *underneath* its
layers — a /domain-forge refine that only ADDED terms (new classes,
individuals, rules) — so that validator invariant 14 holds again. It is not
a fix for a layer that names a renamed or removed term: such a layer is
stale and must be regenerated by its producing skill. `--in-place` is
allowed only with `--restamp`, because the file being re-stamped is the
refine's own output, never the user's input.

Markers printed on stdout: `OK:` / `WARN:` / `ERROR:`.

Exit codes
----------
    0 — wrote OUT.html
    1 — refused (bad layer name, unsafe content, OUT == MODEL, no </body>, …)
    2 — could not read an input file / not a domain-forge model
"""
import argparse
import datetime as _dt
import hashlib
import json
import os
import re
import sys

__all__ = ["apply_layer", "domain_digest", "turtle_body", "is_model", "list_layers",
           "find_layer", "strip_layer", "build_block", "restamp_layers", "utc_now_iso",
           "LAYER_NAME_RE", "REVERTS_BY"]

REVERTS_BY = "open the file at input-digest (the predecessor)"

# Layer names: what both downstream skills use ("chat", "open-questions").
LAYER_NAME_RE = re.compile(r"^[A-Za-z0-9][A-Za-z0-9_-]*$")

# The canonical Turtle block. `domain-model` is what domain-forge emits;
# `model-turtle` is accepted for forward-compatibility (inferred-questions
# accepts it too). The digest covers group(1) verbatim.
_TURTLE_RE = re.compile(
    r'<script\b[^>]*\bid="(?:domain-model|model-turtle)"[^>]*>([\s\S]*?)</script>')

_START_RE = re.compile(
    r"<!--\s*@LAYER:start\s+([A-Za-z0-9][A-Za-z0-9_-]*)(?:\s+v(\d+))?([\s\S]*?)-->")
_END_RE = re.compile(r"<!--\s*@LAYER:end\s+([A-Za-z0-9][A-Za-z0-9_-]*)\s*-->")
_HEADER_FIELD_RE = re.compile(r"^\s*([a-z-]+):\s*(.*?)\s*$")


# --------------------------------------------------------------------------- #
# digest
# --------------------------------------------------------------------------- #
def turtle_body(html):
    """The exact text between the canonical Turtle script's open tag and its
    </script> — what the digest covers — or None if the block is absent."""
    m = _TURTLE_RE.search(html)
    return m.group(1) if m else None


def domain_digest(html):
    """'sha256:' + SHA-256 of the exact bytes between the canonical Turtle
    script's open tag and its </script>. Empty body if the block is absent
    (so the digest still has a value; callers should check is_model first)."""
    body = turtle_body(html) or ""
    return "sha256:" + hashlib.sha256(body.encode("utf-8")).hexdigest()


def is_model(html):
    return _TURTLE_RE.search(html) is not None


# --------------------------------------------------------------------------- #
# layer discovery
# --------------------------------------------------------------------------- #
def _parse_header(text):
    fields = {}
    for line in text.splitlines():
        m = _HEADER_FIELD_RE.match(line)
        if m:
            fields[m.group(1)] = m.group(2)
    return fields


def list_layers(html):
    """Return the well-formed layers in document order.

    Each entry: dict(name, version, produced_by, produced_at, input_digest,
    reverts_by, start, end, header). `start`/`end` are character offsets of
    the block (from the first `<` of @LAYER:start to the last `>` of
    @LAYER:end, exclusive). A start marker without a matching end marker (or a
    nested / overlapping pair) is NOT returned — the validator reports those
    under invariant 13; this function only lists what can be stripped safely.
    """
    layers = []
    pos = 0
    while True:
        s = _START_RE.search(html, pos)
        if not s:
            break
        name = s.group(1)
        end_pat = re.compile(r"<!--\s*@LAYER:end\s+" + re.escape(name) + r"\s*-->")
        e = end_pat.search(html, s.end())
        if not e:
            pos = s.end()
            continue
        # Refuse a block that contains another @LAYER:start (nesting/overlap).
        inner = html[s.end():e.start()]
        if _START_RE.search(inner):
            pos = s.end()
            continue
        fields = _parse_header(s.group(3) or "")
        layers.append(dict(
            name=name,
            version=int(s.group(2)) if s.group(2) else None,
            produced_by=fields.get("produced-by"),
            produced_at=fields.get("produced-at"),
            input_digest=fields.get("input-digest"),
            reverts_by=fields.get("reverts-by"),
            start=s.start(),
            end=e.end(),
            header=s.group(0),
        ))
        pos = e.end()
    return layers


def find_layer(html, name):
    for L in list_layers(html):
        if L["name"] == name:
            return L
    return None


# --------------------------------------------------------------------------- #
# strip
# --------------------------------------------------------------------------- #
def _is_legacy_model_chat_block(L, block_text):
    """True for a `chat` block written by /model-chat's former PRIVATE writer
    (before it delegated to this module). That writer prepended a newline to
    its block and emitted the render tag with no `type` attribute; this
    module always writes `type="text/javascript"`, so the bare tag is the
    signature that tells a legacy file from a current one."""
    return ((L.get("produced_by") or "").strip() == "/model-chat"
            and f'<script id="layer-{L["name"]}-render">' in block_text)


def strip_layer(html, name):
    """Remove the layer block NAME. Exact inverse of apply_layer() for blocks
    this module wrote: the block plus the single trailing newline the writer
    appends. /model-chat and /inferred-questions write through this module,
    so their layers strip the same way.

    Legacy tolerance (named): files produced by /model-chat's former private
    writer carry an extra newline BEFORE the block (see
    _is_legacy_model_chat_block). For those — and only those — the leading
    newline is removed too, so legacy files also round-trip byte-exactly.
    The tolerance must not fire on current blocks: the platform inserts the
    block directly before `</body>`, so any newline preceding it belongs to
    the base model.

    Raises KeyError if the layer is not present.
    """
    L = find_layer(html, name)
    if L is None:
        raise KeyError(name)
    start, end = L["start"], L["end"]
    if html.startswith("\n", end):
        end += 1
    if start > 0 and html[start - 1] == "\n" \
            and _is_legacy_model_chat_block(L, html[start:L["end"]]):
        start -= 1
    return html[:start] + html[end:]


# --------------------------------------------------------------------------- #
# build + apply
# --------------------------------------------------------------------------- #
def utc_now_iso():
    return (_dt.datetime.now(_dt.timezone.utc).replace(microsecond=0)
            .isoformat().replace("+00:00", "Z"))


def _check_safe(kind, text, closing):
    """A block part must not be able to terminate its own container or forge
    layer markers. Returns an error string or None."""
    if closing and re.search(closing, text, re.I):
        return f"{kind} contains {closing!r}; it would terminate its own element"
    if "@LAYER:" in text:
        return f"{kind} contains a literal '@LAYER:' marker; that would forge layer bounds"
    if "-->" in text and kind == "header":
        return "header contains '-->'"
    return None


def build_block(name, data_text, render_js, style_css=None,
                data_type="application/json", produced_by="/unknown",
                version=1, noscript_html=None, produced_at=None,
                input_digest=None):
    """Compose the block text exactly per the contract. `input_digest` must
    be supplied (apply_layer computes it from the input HTML)."""
    if not LAYER_NAME_RE.match(name or ""):
        raise ValueError(f"invalid layer name {name!r} (use [A-Za-z0-9][A-Za-z0-9_-]*)")
    if input_digest is None:
        raise ValueError("input_digest is required")
    produced_at = produced_at or utc_now_iso()
    for kind, text, closing in (("data", data_text, r"</script"),
                                ("render", render_js, r"</script"),
                                ("style", style_css or "", r"</style"),
                                ("noscript", noscript_html or "", r"</noscript")):
        err = _check_safe(kind, text, closing)
        if err:
            raise ValueError(err)
    for kind, val in (("produced-by", produced_by), ("produced-at", produced_at),
                      ("data-type", data_type)):
        if not val or re.search(r"[\r\n]", val) or "-->" in val or '"' in val:
            raise ValueError(f"{kind} must be a single line without '-->' or quotes: {val!r}")

    parts = [
        f"<!-- @LAYER:start {name} v{int(version)}\n"
        f"     produced-by: {produced_by}\n"
        f"     produced-at: {produced_at}\n"
        f"     input-digest: {input_digest}\n"
        f"     reverts-by: {REVERTS_BY}\n"
        f" -->",
        f'<script id="layer-{name}-data" type="{data_type}">\n{data_text}\n</script>',
        f'<script id="layer-{name}-render" type="text/javascript">\n{render_js}\n</script>',
    ]
    if style_css is not None:
        parts.append(f'<style id="layer-{name}-style">\n{style_css}\n</style>')
    if noscript_html is not None:
        parts.append(f"<noscript>\n{noscript_html}\n</noscript>")
    parts.append(f"<!-- @LAYER:end {name} -->")
    return "\n".join(parts) + "\n"


def apply_layer(html, name, data_text, render_js, style_css=None,
                data_type="application/json", produced_by="/unknown",
                version=1, noscript_html=None, produced_at=None,
                report=None):
    """Return HTML with layer NAME inserted before the last </body>.

    If NAME already exists it is stripped first (create-or-update). `report`,
    when given, is called with human-readable notes (e.g. the replacement
    notice) so a CLI can print them. Raises ValueError on refusal.
    """
    if not is_model(html):
        raise ValueError('not a domain-forge model (no <script id="domain-model"> block)')
    base = html
    if find_layer(html, name):
        base = strip_layer(html, name)
        if report:
            report(f"layer {name!r} already present in the input — replaced "
                   f"(output is NOT a byte superset of the input for this run)")
    idx = base.rfind("</body>")
    if idx < 0:
        raise ValueError("could not locate </body> in the input; refusing to insert")
    digest = domain_digest(base)
    block = build_block(name, data_text, render_js, style_css=style_css,
                        data_type=data_type, produced_by=produced_by,
                        version=version, noscript_html=noscript_html,
                        produced_at=produced_at, input_digest=digest)
    out = base[:idx] + block + base[idx:]
    # Superset self-check against the (possibly stripped) base.
    assert out[:idx] == base[:idx] and out[idx + len(block):] == base[idx:]
    return out


# --------------------------------------------------------------------------- #
# CLI
# --------------------------------------------------------------------------- #
def restamp_layers(html, report=None):
    """Return html with every layer's input-digest set to the current digest.

    Returns (new_html, [names re-stamped]). Layers whose digest already
    matches are left untouched. Only the `input-digest:` line inside each
    `@LAYER:start` header is rewritten; every other byte is preserved.
    """
    current = domain_digest(html)
    changed = []
    out = html
    for L in reversed(list_layers(html)):  # right-to-left so offsets stay valid
        if L["input_digest"] == current:
            continue
        head_end = out.find("-->", L["start"])
        header = out[L["start"]:head_end]
        new_header = re.sub(r"(input-digest:\s*)\S+", r"\g<1>" + current, header, count=1)
        if new_header == header:
            if report:
                report(f"layer {L['name']}: no input-digest field to re-stamp")
            continue
        out = out[:L["start"]] + new_header + out[head_end:]
        changed.append(L["name"])
    return out, list(reversed(changed))


def _read(path, what):
    try:
        with open(path, encoding="utf-8") as fh:
            return fh.read()
    except OSError as e:
        print(f"ERROR: cannot read {what} {path}: {e}")
        sys.exit(2)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Insert a pure-additive @LAYER block into a domain-forge model.")
    ap.add_argument("model", help="input MODEL.html (never modified, except --restamp --in-place)")
    ap.add_argument("--layer", help="layer NAME")
    ap.add_argument("--data", help="file whose text becomes layer-NAME-data")
    ap.add_argument("--render", help="JS file whose text becomes layer-NAME-render")
    ap.add_argument("--restamp", action="store_true",
                    help="rewrite every layer's input-digest to the current canonical-Turtle digest")
    ap.add_argument("--in-place", action="store_true",
                    help="with --restamp only: write back to MODEL.html")
    ap.add_argument("--style", help="CSS file whose text becomes layer-NAME-style")
    ap.add_argument("--data-type", default="application/json",
                    help="type attribute of the data script (default application/json)")
    ap.add_argument("--produced-by", default="/unknown", help='e.g. "/model-chat"')
    ap.add_argument("--version", type=int, default=1)
    ap.add_argument("--noscript", help="HTML file whose text becomes a <noscript> fallback")
    ap.add_argument("--produced-at", help="override the UTC ISO timestamp (tests)")
    ap.add_argument("--out", help="output path (must differ from MODEL)")
    a = ap.parse_args(argv)

    if a.restamp:
        if a.layer or a.data or a.render:
            print("ERROR: --restamp takes no --layer/--data/--render")
            return 1
        if bool(a.out) == bool(a.in_place):
            print("ERROR: --restamp needs exactly one of --out OUT.html or --in-place")
            return 1
        html = _read(a.model, "model")
        if not is_model(html):
            print('ERROR: input is not a domain-forge model (no <script id="domain-model"> block)')
            return 2
        notes = []
        out, changed = restamp_layers(html, report=notes.append)
        for n in notes:
            print(f"WARN: {n}")
        target = a.model if a.in_place else a.out
        with open(target, "w", encoding="utf-8") as fh:
            fh.write(out)
        if changed:
            print(f"OK: re-stamped {len(changed)} layer(s) in {target}: {', '.join(changed)} -> {domain_digest(out)}")
            print("WARN: re-stamping asserts the layers are still valid against the edited base model; "
                  "a layer that names a renamed or removed term must be regenerated instead")
        else:
            print(f"OK: {target}: every layer already matches the current digest; nothing re-stamped")
        return 0

    if not (a.layer and a.data and a.render and a.out):
        print("ERROR: --layer, --data, --render and --out are required (or use --restamp)")
        return 1
    if a.in_place:
        print("ERROR: --in-place is allowed only with --restamp; the input is never modified")
        return 1
    if os.path.abspath(a.out) == os.path.abspath(a.model) or (
            os.path.exists(a.out) and os.path.samefile(a.out, a.model)):
        print(f"ERROR: --out resolves to the input path {a.model}; the input is never modified")
        return 1
    if not LAYER_NAME_RE.match(a.layer):
        print(f"ERROR: invalid layer name {a.layer!r} (use [A-Za-z0-9][A-Za-z0-9_-]*)")
        return 1

    html = _read(a.model, "model")
    if not is_model(html):
        print('ERROR: input is not a domain-forge model (no <script id="domain-model"> block)')
        return 2
    data_text = _read(a.data, "data file")
    render_js = _read(a.render, "render file")
    style_css = _read(a.style, "style file") if a.style else None
    noscript = _read(a.noscript, "noscript file") if a.noscript else None

    if a.data_type in ("application/json", "application/ld+json"):
        try:
            json.loads(data_text)
        except Exception as e:
            print(f"ERROR: --data is not valid JSON but --data-type is {a.data_type}: {e}")
            return 1

    notes = []
    try:
        out = apply_layer(html, a.layer, data_text, render_js, style_css=style_css,
                          data_type=a.data_type, produced_by=a.produced_by,
                          version=a.version, noscript_html=noscript,
                          produced_at=a.produced_at, report=notes.append)
    except ValueError as e:
        print(f"ERROR: {e}")
        return 1
    for n in notes:
        print(f"WARN: {n}")
    with open(a.out, "w", encoding="utf-8") as fh:
        fh.write(out)
    L = find_layer(out, a.layer)
    print(f"OK: wrote {a.out} (layer={a.layer} v{a.version}, produced-by={a.produced_by}, "
          f"input-digest={L['input_digest']}, {len(out) - len(html):+d} chars"
          f"{', replaced existing layer' if notes else ', strict superset of input'})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
